export const data = {
  'sp': {
    name: 'Hola, soy',
    info: 'Desarrollador web de 📍Argentina. Apasionado, proactivo y autodidacta, con un profundo entusiasmo por las tecnologías web emergentes y un compromiso con las tendencias de la industria.',
    btnHire: 'Contrátame',
    btnDownload: 'Descargar CV',
    linkCv: 'https://drive.google.com/uc?export=download&id=1hcohX3gwFY9iEoJKmU20RLwE_JrOXRBt',
    titleAboutMe: 'Sobre mí',
    textAboutMe: 'Con más de 5 años de experiencia, he desarrollado sitios con las mejores prácticas utilizando herramientas Frontend y Backend, priorizando el buen desempeño. Cuando no estoy frente a la computadora, suelo estar dibujando o aprendiendo música 🎶.',
    optionsAboutMe: [ 'Herramientas', 'Educación' ],
    titleProjects: 'Mis Projectos',
    titleContact: 'Conectémonos',
    textContact: 'Actualmente estoy buscando nuevas oportunidades. Mi bandeja de entrada siempre está abierta. Si tienes alguna pregunta o simplemente quieres saludarme, haré todo lo posible por responderte.',
    textFooter: `® ${new Date().getFullYear()} Todos los derechos reservados.`,
  },
  'en': {
    name: "Hello, I'm",
    info: "a Web Developer from 📍Argentina. Passionate, proactive, and self-taught, with a deep enthusiasm for emerging web technologies and a commitment to staying current with industry trends.",
    btnHire: 'Hire me',
    btnDownload: 'Download CV',
    linkCv: 'https://drive.google.com/uc?export=download&id=1z0mexfX4rbTGWZgghY8PrdIcBKJbWyVN',
    titleAboutMe: 'About Me',
    textAboutMe: "With more than 5 years of experience, I have developed sites with best practices using Frontend and backend tools, prioritizing good performance. When I'm not at the computer, I'm usually drawing or learning music 🎶.",
    optionsAboutMe: [ 'Skills', 'Education' ],
    titleProjects: 'My Projects',
    titleContact: "Let's Connect",
    textContact: "I'm currently looking for new opportunities, my inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!",
    textFooter: `® ${new Date().getFullYear()} All rights reserved.`,
  },
};