export const data = {
  'sp': {
    nameHero: 'Hola, soy',
    infoHero: 'Un desarrollador full stack de Argentina, comprometido en transformar ideas en soluciones digitales efectivas. 💡 Apasionado por la tecnología, proactivo y siempre al día con las tendencias más innovadoras de la industria.',
    missionHero: '🚀 Mi misión es crear experiencias web que combinen funcionalidad, diseño y rendimiento.',
    btnHire: 'Contáctame',
    btnDownload: 'Descargar CV',
    linkCv: 'https://drive.google.com/uc?export=download&id=15uoEhZRkmWfK024jJYindCiSAJEpPAFE',
    titleAboutMe: 'Sobre mí',
    textAboutMe: 'Con más de 5 años de experiencia, me especializo en desarrollar sistemas con las mejores prácticas priorizando la seguridad, escalabilidad y una buena performance. Capacidad de implementar pruebas unitarias y pruebas end-to-end. Experiencia trabajando en equipo utilizando GIT para la gestión de versiones del proyecto. Desarrollo y mantenimiento de APIs REST con Node.js o C# .NET. Dominio de Bases de Datos SQL y NoSql para optimización de operaciones y procedimientos.',
    optionsAboutMe: [ 'Herramientas', 'Educación' ],
    textEducation: 'UTN FRC - Tecnicatura Universitaria en Programación',
    titleProjects: 'Mis Projectos',
    titleContact: 'Conectémonos',
    textContact: 'Actualmente estoy buscando nuevas oportunidades. Mi bandeja de entrada siempre está abierta para cualquier pregunta que tengas. ¡Haré todo lo posible por responderte!',
    textFooter: `® ${new Date().getFullYear()} Todos los derechos reservados.`,
  },
  'en': {
    nameHero: "Hello, I'm",
    infoHero: "A full-stack developer from Argentina, committed to transforming ideas into effective digital solutions. 💡 Passionate about technology, proactive, and always up to date with the most innovative trends in the industry.",
    missionHero: '🚀 My mission is to create web experiences that combine functionality, design and performance.',
    btnHire: 'Contact me',
    btnDownload: 'Download CV',
    linkCv: 'https://drive.google.com/uc?export=download&id=1O6NTW58a6WJUCgwNan_Bp9eQRTX394L1',
    titleAboutMe: 'About Me',
    textAboutMe: "With +5 years of experience, I specialize in creating systems using best practices prioritizing security, scalability and good performance. Skilled in implementing unit tests and end-to-end tests. Experienced in teamwork using GIT for version control. Proficient in developing and maintaining REST APIs with Node.js or C# .NET. Expertise in SQL and NoSQL databases for optimizing operations and procedures.",
    optionsAboutMe: [ 'Skills', 'Education' ],
    textEducation: 'UTN FRC - University Degree in Programming',
    titleProjects: 'My Projects',
    titleContact: "Let's Connect",
    textContact: "I'm currently looking for new opportunities. My inbox is always open for any questions you may have. I'll do my best to answer!",
    textFooter: `® ${new Date().getFullYear()} All rights reserved.`,
  },
};
// textContact: "I'm currently looking for new opportunities, my inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!",
