export const projectsData = [
  {
    title: "Poke Dex",
    description: 'a responsive Pokédex designed for exploring the Pokémon and their characteristics.',
    image: "https://github.com/user-attachments/assets/57ad397c-6c86-4cc1-83aa-a939a7ff2d54",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/poke-dex",
    previewUrl: "https://pokedex-psi-hazel.vercel.app/welcome",
  },
  {
    title: "Crypto Quoter",
    description: "a lightweight cryptocurrency quotation tool that allows users to check real-time prices of various cryptocurrencies in different fiat currencies.",
    image: "https://github.com/user-attachments/assets/b3e167a3-5801-4f62-970b-2370beb7e4bd",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/crypto-quoter-ts",
    previewUrl: "https://lgimenez-code.github.io/crypto-quoter-ts/",
  },
  {
    title: "Wallet Landing Page",
    description: "landing page for a wallet, designed to explore the features offered by the product as well as the benefits it brings.",
    image: "https://github.com/user-attachments/assets/a79c466c-ba99-46a4-9e0f-eeace0224f08",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/wallet-page",
    previewUrl: "https://lgimenez-code.github.io/wallet-page/",
  },
  {
    title: "Mini Market Shop",
    description: "RESTful API developed in .NET for managing products, categories, and suppliers of a store.",
    image: "https://github.com/user-attachments/assets/e29dd67e-8c83-4a00-95b9-741fe042f515",
    tag: ["All", "Backend"],
    gitUrl: "https://github.com/lgimenez-code/TinyMarket",
    previewUrl: "",
  },
  {
    title: "Scraper App",
    description: ".NET console application that extracts book information from a sample website.",
    image: "https://github.com/user-attachments/assets/bf9bbd97-2968-4173-a6f4-af3b92ed447e",
    tag: ["All", "Backend"],
    gitUrl: "https://github.com/lgimenez-code/scraper",
    previewUrl: "",
  },
];