export const projectsData = [
  {
    id: 0,
    title: "Poke Dex",
    description: 'a responsive Pokédex designed for exploring the Pokémon and their characteristics.',
    image: "https://github.com/user-attachments/assets/57ad397c-6c86-4cc1-83aa-a939a7ff2d54",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/poke-dex",
    previewUrl: "https://pokedex-psi-hazel.vercel.app/welcome",
  },
  {
    id: 1,
    title: "Chat IA",
    description: 'chat project that uses Google "Gemini" IA to deliver fast and accurate responses. ',
    image: "https://github.com/user-attachments/assets/eef2da83-f478-4482-a818-5e9e908748f3",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/kianoIA",
    previewUrl: "https://kiano-ia.vercel.app/",
  },
  {
    id: 2,
    title: "Crypto App",
    description: "an app to check the price of the selected cryptocurrency",
    image: "https://github.com/user-attachments/assets/b2189b02-89bb-401d-a2ae-bb013b8f0969",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/crypto-quoter",
    previewUrl: "https://crypto-quoter-rho.vercel.app/",
  },
  {
    id: 3,
    title: "Scraper App",
    description: ".NET console application that extracts book information from a sample website.",
    image: "https://github.com/user-attachments/assets/bf9bbd97-2968-4173-a6f4-af3b92ed447e",
    tag: ["All", "Backend"],
    gitUrl: "https://github.com/lgimenez-code/scraper",
    previewUrl: "",
  },
  {
    id: 4,
    title: "Wallet Landing Page",
    description: "landing page for a wallet, designed to explore the features offered by the product as well as the benefits it brings.",
    image: "https://github.com/user-attachments/assets/a79c466c-ba99-46a4-9e0f-eeace0224f08",
    tag: ["All", "Frontend"],
    gitUrl: "https://github.com/lgimenez-code/wallet-page",
    previewUrl: "https://lgimenez-code.github.io/wallet-page/",
  },
];